# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check the build.gradle files instead.

# When configured, Gradle will run in offline mode and disables dependency
# verification over HTTP.
#org.gradle.offline=true

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and excludes resources from dependencies,
# thereby reducing the size of the R class for that library
android.nonTransitiveRClass=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# The Android Gradle plugin requires Java 11.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

